root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/app ./cmd"
bin = "tmp/app"
full_bin = "APP_ENV=dev ./tmp/app"
include_ext = ["go"]
exclude_dir = ["tmp", "vendor", "frontend/node_modules"]
exclude_regex = ["_test\\.go"]
stop_on_error = true

[log]
time = false

[misc]
clean_on_exit = true
